version: '3.8'

services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: MicroservicesDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  eureka:
    build: ./Ecomm_EurekaServer
    container_name: eureka
    ports:
      - "8761:8761"
    restart: always

  config:
    build: ./Ecomm_ConfigServer
    container_name: config
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    restart: always

  gateway:
    build: ./APIGateway
    container_name: gateway
    ports:
      - "8081:8080"
    depends_on:
      - config
      - eureka
    restart: always

  product:
    build: ./Product
    container_name: product
    depends_on:
      - config
      - postgres-db
    restart: always

  catalog:
    build: ./ProductCatalog
    container_name: catalog
    depends_on:
      - config
      - postgres-db
    restart: always

  inventory:
    build: ./ProductInventory
    container_name: inventory
    depends_on:
      - config
      - postgres-db
    restart: always

  price:
    build: ./ProductPrice
    container_name: price
    depends_on:
      - config
      - postgres-db
    restart: always

  cart:
    build: ./Cart
    container_name: cart
    ports:
      - "8082:8082"
    depends_on:
      - config
    restart: always

  recommendation:
    build: ./Recommendation
    container_name: recommendation
    ports:
      - "8083:8083"
    depends_on:
      - config
    restart: always
