spring.application.name=ProductPrice


spring.datasource.url=jdbc:postgresql://postgres-db:5432/MicroservicesDB
spring.datasource.username=user
spring.datasource.password=password

spring.config.import=configserver:http://config:8888
