spring.application.name=Product

spring.datasource.url=jdbc:postgresql://postgres-db:5432/MicroservicesDB
spring.datasource.username=user
spring.datasource.password=password

spring.config.import=configserver:http://config-server:8888


# Enable Micrometer tracing
management.tracing.enabled=true

# URL of running Zipkin server
management.tracing.zipkin.endpoint=http://zipkin:9411/api/v2/spans

# Always sample (for testing)
management.tracing.sampling.probability=1.0