apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-price
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-price
  template:
    metadata:
      labels:
        app: product-price
    spec:
      containers:
      - name: product-price
        image: product-price:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8052