apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-stock
  namespace: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-stock
  template:
    metadata:
      labels:
        app: product-stock
    spec:
      containers:
      - name: product-stock
        image: product-inventory:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8053