apiVersion: v1
kind: Service
metadata:
  name: ecommerce-db
  namespace: ecommerce-app
spec:
  clusterIP: None
  selector:
    app: ecommerce-db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecommerce-db
  namespace: ecommerce-app
spec:
  serviceName: ecommerce-db
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-db
  template:
    metadata:
      labels:
        app: ecommerce-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432