spring.application.name=Cart

spring.datasource.url=jdbc:postgresql://postgres-db:5432/MicroservicesDB
spring.datasource.username=user
spring.datasource.password=password


spring.config.import=configserver:http://config-server:8888



resilience4j.circuitbreaker.instances.catalogService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.catalogService.slidingWindowSize= 5
resilience4j.circuitbreaker.instances.catalogService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.catalogService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.catalogService.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.catalogService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.catalogService.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.catalogService.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.catalogService.slidingWindowType=COUNT_BASED


management.health.circuitbreakers.enabled=true
management.endpoint.circuitbreakers.enabled=true